// Code generated by counterfeiter. DO NOT EDIT.
package agentfakes

import (
	"context"
	"sync"

	"code.cloudfoundry.org/k8s-policy-agent/internal/agent"
	"code.cloudfoundry.org/k8s-policy-agent/internal/cni"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/manager"
)

type FakeRuntimeManager struct {
	AddStub        func(manager.Runnable) error
	addMutex       sync.RWMutex
	addArgsForCall []struct {
		arg1 manager.Runnable
	}
	addReturns struct {
		result1 error
	}
	addReturnsOnCall map[int]struct {
		result1 error
	}
	KubernetesClientStub        func() client.Client
	kubernetesClientMutex       sync.RWMutex
	kubernetesClientArgsForCall []struct {
	}
	kubernetesClientReturns struct {
		result1 client.Client
	}
	kubernetesClientReturnsOnCall map[int]struct {
		result1 client.Client
	}
	StartStub        func(context.Context) error
	startMutex       sync.RWMutex
	startArgsForCall []struct {
		arg1 context.Context
	}
	startReturns struct {
		result1 error
	}
	startReturnsOnCall map[int]struct {
		result1 error
	}
	TranslatorStub        func() cni.Translator
	translatorMutex       sync.RWMutex
	translatorArgsForCall []struct {
	}
	translatorReturns struct {
		result1 cni.Translator
	}
	translatorReturnsOnCall map[int]struct {
		result1 cni.Translator
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRuntimeManager) Add(arg1 manager.Runnable) error {
	fake.addMutex.Lock()
	ret, specificReturn := fake.addReturnsOnCall[len(fake.addArgsForCall)]
	fake.addArgsForCall = append(fake.addArgsForCall, struct {
		arg1 manager.Runnable
	}{arg1})
	stub := fake.AddStub
	fakeReturns := fake.addReturns
	fake.recordInvocation("Add", []interface{}{arg1})
	fake.addMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRuntimeManager) AddCallCount() int {
	fake.addMutex.RLock()
	defer fake.addMutex.RUnlock()
	return len(fake.addArgsForCall)
}

func (fake *FakeRuntimeManager) AddCalls(stub func(manager.Runnable) error) {
	fake.addMutex.Lock()
	defer fake.addMutex.Unlock()
	fake.AddStub = stub
}

func (fake *FakeRuntimeManager) AddArgsForCall(i int) manager.Runnable {
	fake.addMutex.RLock()
	defer fake.addMutex.RUnlock()
	argsForCall := fake.addArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeRuntimeManager) AddReturns(result1 error) {
	fake.addMutex.Lock()
	defer fake.addMutex.Unlock()
	fake.AddStub = nil
	fake.addReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeRuntimeManager) AddReturnsOnCall(i int, result1 error) {
	fake.addMutex.Lock()
	defer fake.addMutex.Unlock()
	fake.AddStub = nil
	if fake.addReturnsOnCall == nil {
		fake.addReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.addReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeRuntimeManager) KubernetesClient() client.Client {
	fake.kubernetesClientMutex.Lock()
	ret, specificReturn := fake.kubernetesClientReturnsOnCall[len(fake.kubernetesClientArgsForCall)]
	fake.kubernetesClientArgsForCall = append(fake.kubernetesClientArgsForCall, struct {
	}{})
	stub := fake.KubernetesClientStub
	fakeReturns := fake.kubernetesClientReturns
	fake.recordInvocation("KubernetesClient", []interface{}{})
	fake.kubernetesClientMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRuntimeManager) KubernetesClientCallCount() int {
	fake.kubernetesClientMutex.RLock()
	defer fake.kubernetesClientMutex.RUnlock()
	return len(fake.kubernetesClientArgsForCall)
}

func (fake *FakeRuntimeManager) KubernetesClientCalls(stub func() client.Client) {
	fake.kubernetesClientMutex.Lock()
	defer fake.kubernetesClientMutex.Unlock()
	fake.KubernetesClientStub = stub
}

func (fake *FakeRuntimeManager) KubernetesClientReturns(result1 client.Client) {
	fake.kubernetesClientMutex.Lock()
	defer fake.kubernetesClientMutex.Unlock()
	fake.KubernetesClientStub = nil
	fake.kubernetesClientReturns = struct {
		result1 client.Client
	}{result1}
}

func (fake *FakeRuntimeManager) KubernetesClientReturnsOnCall(i int, result1 client.Client) {
	fake.kubernetesClientMutex.Lock()
	defer fake.kubernetesClientMutex.Unlock()
	fake.KubernetesClientStub = nil
	if fake.kubernetesClientReturnsOnCall == nil {
		fake.kubernetesClientReturnsOnCall = make(map[int]struct {
			result1 client.Client
		})
	}
	fake.kubernetesClientReturnsOnCall[i] = struct {
		result1 client.Client
	}{result1}
}

func (fake *FakeRuntimeManager) Start(arg1 context.Context) error {
	fake.startMutex.Lock()
	ret, specificReturn := fake.startReturnsOnCall[len(fake.startArgsForCall)]
	fake.startArgsForCall = append(fake.startArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.StartStub
	fakeReturns := fake.startReturns
	fake.recordInvocation("Start", []interface{}{arg1})
	fake.startMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRuntimeManager) StartCallCount() int {
	fake.startMutex.RLock()
	defer fake.startMutex.RUnlock()
	return len(fake.startArgsForCall)
}

func (fake *FakeRuntimeManager) StartCalls(stub func(context.Context) error) {
	fake.startMutex.Lock()
	defer fake.startMutex.Unlock()
	fake.StartStub = stub
}

func (fake *FakeRuntimeManager) StartArgsForCall(i int) context.Context {
	fake.startMutex.RLock()
	defer fake.startMutex.RUnlock()
	argsForCall := fake.startArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeRuntimeManager) StartReturns(result1 error) {
	fake.startMutex.Lock()
	defer fake.startMutex.Unlock()
	fake.StartStub = nil
	fake.startReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeRuntimeManager) StartReturnsOnCall(i int, result1 error) {
	fake.startMutex.Lock()
	defer fake.startMutex.Unlock()
	fake.StartStub = nil
	if fake.startReturnsOnCall == nil {
		fake.startReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.startReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeRuntimeManager) Translator() cni.Translator {
	fake.translatorMutex.Lock()
	ret, specificReturn := fake.translatorReturnsOnCall[len(fake.translatorArgsForCall)]
	fake.translatorArgsForCall = append(fake.translatorArgsForCall, struct {
	}{})
	stub := fake.TranslatorStub
	fakeReturns := fake.translatorReturns
	fake.recordInvocation("Translator", []interface{}{})
	fake.translatorMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRuntimeManager) TranslatorCallCount() int {
	fake.translatorMutex.RLock()
	defer fake.translatorMutex.RUnlock()
	return len(fake.translatorArgsForCall)
}

func (fake *FakeRuntimeManager) TranslatorCalls(stub func() cni.Translator) {
	fake.translatorMutex.Lock()
	defer fake.translatorMutex.Unlock()
	fake.TranslatorStub = stub
}

func (fake *FakeRuntimeManager) TranslatorReturns(result1 cni.Translator) {
	fake.translatorMutex.Lock()
	defer fake.translatorMutex.Unlock()
	fake.TranslatorStub = nil
	fake.translatorReturns = struct {
		result1 cni.Translator
	}{result1}
}

func (fake *FakeRuntimeManager) TranslatorReturnsOnCall(i int, result1 cni.Translator) {
	fake.translatorMutex.Lock()
	defer fake.translatorMutex.Unlock()
	fake.TranslatorStub = nil
	if fake.translatorReturnsOnCall == nil {
		fake.translatorReturnsOnCall = make(map[int]struct {
			result1 cni.Translator
		})
	}
	fake.translatorReturnsOnCall[i] = struct {
		result1 cni.Translator
	}{result1}
}

func (fake *FakeRuntimeManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRuntimeManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ agent.RuntimeManager = new(FakeRuntimeManager)
