// Code generated by counterfeiter. DO NOT EDIT.
package agentfakes

import (
	"sync"

	"code.cloudfoundry.org/k8s-policy-agent/internal/agent"
	"code.cloudfoundry.org/policy_client"
)

type FakePolicyServerClient struct {
	GetPoliciesStub        func() ([]*policy_client.Policy, error)
	getPoliciesMutex       sync.RWMutex
	getPoliciesArgsForCall []struct {
	}
	getPoliciesReturns struct {
		result1 []*policy_client.Policy
		result2 error
	}
	getPoliciesReturnsOnCall map[int]struct {
		result1 []*policy_client.Policy
		result2 error
	}
	GetSecurityGroupsForSpaceStub        func(...string) ([]policy_client.SecurityGroup, error)
	getSecurityGroupsForSpaceMutex       sync.RWMutex
	getSecurityGroupsForSpaceArgsForCall []struct {
		arg1 []string
	}
	getSecurityGroupsForSpaceReturns struct {
		result1 []policy_client.SecurityGroup
		result2 error
	}
	getSecurityGroupsForSpaceReturnsOnCall map[int]struct {
		result1 []policy_client.SecurityGroup
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakePolicyServerClient) GetPolicies() ([]*policy_client.Policy, error) {
	fake.getPoliciesMutex.Lock()
	ret, specificReturn := fake.getPoliciesReturnsOnCall[len(fake.getPoliciesArgsForCall)]
	fake.getPoliciesArgsForCall = append(fake.getPoliciesArgsForCall, struct {
	}{})
	stub := fake.GetPoliciesStub
	fakeReturns := fake.getPoliciesReturns
	fake.recordInvocation("GetPolicies", []interface{}{})
	fake.getPoliciesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePolicyServerClient) GetPoliciesCallCount() int {
	fake.getPoliciesMutex.RLock()
	defer fake.getPoliciesMutex.RUnlock()
	return len(fake.getPoliciesArgsForCall)
}

func (fake *FakePolicyServerClient) GetPoliciesCalls(stub func() ([]*policy_client.Policy, error)) {
	fake.getPoliciesMutex.Lock()
	defer fake.getPoliciesMutex.Unlock()
	fake.GetPoliciesStub = stub
}

func (fake *FakePolicyServerClient) GetPoliciesReturns(result1 []*policy_client.Policy, result2 error) {
	fake.getPoliciesMutex.Lock()
	defer fake.getPoliciesMutex.Unlock()
	fake.GetPoliciesStub = nil
	fake.getPoliciesReturns = struct {
		result1 []*policy_client.Policy
		result2 error
	}{result1, result2}
}

func (fake *FakePolicyServerClient) GetPoliciesReturnsOnCall(i int, result1 []*policy_client.Policy, result2 error) {
	fake.getPoliciesMutex.Lock()
	defer fake.getPoliciesMutex.Unlock()
	fake.GetPoliciesStub = nil
	if fake.getPoliciesReturnsOnCall == nil {
		fake.getPoliciesReturnsOnCall = make(map[int]struct {
			result1 []*policy_client.Policy
			result2 error
		})
	}
	fake.getPoliciesReturnsOnCall[i] = struct {
		result1 []*policy_client.Policy
		result2 error
	}{result1, result2}
}

func (fake *FakePolicyServerClient) GetSecurityGroupsForSpace(arg1 ...string) ([]policy_client.SecurityGroup, error) {
	fake.getSecurityGroupsForSpaceMutex.Lock()
	ret, specificReturn := fake.getSecurityGroupsForSpaceReturnsOnCall[len(fake.getSecurityGroupsForSpaceArgsForCall)]
	fake.getSecurityGroupsForSpaceArgsForCall = append(fake.getSecurityGroupsForSpaceArgsForCall, struct {
		arg1 []string
	}{arg1})
	stub := fake.GetSecurityGroupsForSpaceStub
	fakeReturns := fake.getSecurityGroupsForSpaceReturns
	fake.recordInvocation("GetSecurityGroupsForSpace", []interface{}{arg1})
	fake.getSecurityGroupsForSpaceMutex.Unlock()
	if stub != nil {
		return stub(arg1...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakePolicyServerClient) GetSecurityGroupsForSpaceCallCount() int {
	fake.getSecurityGroupsForSpaceMutex.RLock()
	defer fake.getSecurityGroupsForSpaceMutex.RUnlock()
	return len(fake.getSecurityGroupsForSpaceArgsForCall)
}

func (fake *FakePolicyServerClient) GetSecurityGroupsForSpaceCalls(stub func(...string) ([]policy_client.SecurityGroup, error)) {
	fake.getSecurityGroupsForSpaceMutex.Lock()
	defer fake.getSecurityGroupsForSpaceMutex.Unlock()
	fake.GetSecurityGroupsForSpaceStub = stub
}

func (fake *FakePolicyServerClient) GetSecurityGroupsForSpaceArgsForCall(i int) []string {
	fake.getSecurityGroupsForSpaceMutex.RLock()
	defer fake.getSecurityGroupsForSpaceMutex.RUnlock()
	argsForCall := fake.getSecurityGroupsForSpaceArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakePolicyServerClient) GetSecurityGroupsForSpaceReturns(result1 []policy_client.SecurityGroup, result2 error) {
	fake.getSecurityGroupsForSpaceMutex.Lock()
	defer fake.getSecurityGroupsForSpaceMutex.Unlock()
	fake.GetSecurityGroupsForSpaceStub = nil
	fake.getSecurityGroupsForSpaceReturns = struct {
		result1 []policy_client.SecurityGroup
		result2 error
	}{result1, result2}
}

func (fake *FakePolicyServerClient) GetSecurityGroupsForSpaceReturnsOnCall(i int, result1 []policy_client.SecurityGroup, result2 error) {
	fake.getSecurityGroupsForSpaceMutex.Lock()
	defer fake.getSecurityGroupsForSpaceMutex.Unlock()
	fake.GetSecurityGroupsForSpaceStub = nil
	if fake.getSecurityGroupsForSpaceReturnsOnCall == nil {
		fake.getSecurityGroupsForSpaceReturnsOnCall = make(map[int]struct {
			result1 []policy_client.SecurityGroup
			result2 error
		})
	}
	fake.getSecurityGroupsForSpaceReturnsOnCall[i] = struct {
		result1 []policy_client.SecurityGroup
		result2 error
	}{result1, result2}
}

func (fake *FakePolicyServerClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakePolicyServerClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ agent.PolicyServerClient = new(FakePolicyServerClient)
