resources: ~
pollInterval: 5s

policyServer:
  address: https://policy-server.{{ .Release.Namespace }}.svc.cluster.local:4003

image:
  repository: ghcr.io/cloudfoundry/k8s/policy-agent
  pullPolicy: IfNotPresent
  tag: ""

certificateSecret: ""

nodeSelector: ~
tolerations: ~

cni: ""
