name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version-file: "go.mod"
    - name: Evaluate Go version
      shell: bash
      run: |
        GOVERSION=$(go version | awk '{print $3}' | sed 's/\.[0-9]*$//')
        echo "GOFLAGS=-gcflags=all=-lang=${GOVERSION}" >> $GITHUB_ENV
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v9
      with:
        only-new-issues: true

  unit:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version-file: "go.mod"
    - name: Evaluate Go version
      shell: bash
      run: |
        GOVERSION=$(go version | awk '{print $3}' | sed 's/\.[0-9]*$//')
        echo "GOFLAGS=-gcflags=all=-lang=${GOVERSION}" >> $GITHUB_ENV
    - name: unit-test
      run: make unit
    - uses: gwatts/go-coverage-action@v2
      id: coverage
      with:
        coverage-threshold: 70
        fail-coverage: true
        test-pkgs: ./internal/...
        test-args: '["-short", "-vet=off"]'
        ignore-pattern: |
          .*/stubs/.*$
          .*/.*fakes/.*$
          .*/internal/client/.*$

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version-file: "go.mod"
    - name: Evaluate Go version
      shell: bash
      run: |
        GOVERSION=$(go version | awk '{print $3}' | sed 's/\.[0-9]*$//')
        echo "GOFLAGS=-gcflags=all=-lang=${GOVERSION}" >> $GITHUB_ENV
    - name: Build container image
      run: make image

  integration:
    runs-on: ubuntu-latest
    needs: [lint, unit, build]
    strategy:
      matrix:
        cni: [integration-calico, integration-cilium]
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version-file: "go.mod"
    - name: Evaluate Go version
      shell: bash
      run: |
        GOVERSION=$(go version | awk '{print $3}' | sed 's/\.[0-9]*$//')
        echo "GOFLAGS=-gcflags=all=-lang=${GOVERSION}" >> $GITHUB_ENV
    - name: Run integration tests
      run: make ${{ matrix.cni }}

  draft-release:
    runs-on: ubuntu-latest
    needs: [integration]
    if: github.ref_name == 'main'
    permissions:
      contents: write
    steps:
      - uses: release-drafter/release-drafter@v7
        env:
          GITHUB_TOKEN: ${{ secrets.SERVICE_USER_GITHUB_TOKEN }}
